# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/a.elkhouly/Desktop/Proj/Proj.cache/wt [current_project]
set_property parent.project_path C:/Users/a.elkhouly/Desktop/Proj/Proj.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:basys3:part0:1.1 [current_project]
set_property ip_output_repo c:/Users/a.elkhouly/Desktop/Proj/Proj.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib C:/Users/a.elkhouly/Desktop/Proj/Proj.srcs/sources_1/new/count.v
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/a.elkhouly/Desktop/Proj/Proj.srcs/constrs_1/new/const.xdc
set_property used_in_implementation false [get_files C:/Users/a.elkhouly/Desktop/Proj/Proj.srcs/constrs_1/new/const.xdc]


synth_design -top count -part xc7a35tcpg236-1


write_checkpoint -force -noxdef count.dcp

catch { report_utilization -file count_utilization_synth.rpt -pb count_utilization_synth.pb }
